### ISSUE TITLE
Create New Recording goes to blank screen

### ISSUE THREAD

**Issue by gavspav** [roundware/roundware-web-template#10]
If I upload and submit an MP3 file, I am given the choice of 'listen' or 'create new recoding'
If I select create new recording it takes me to the speak page but this is blank.
This may well be related to me skipping the tag questions though.

**Comment by hburgund** [comment]
I think this is fixed by the most recent code on my developer's fork:

https://github.com/shreyas-jadhav/roundware-web-template/commits/main

Have a look and LMK.

**Comment by gavspav** [comment]
Well I manually changed the code to incorporate the last commit from that fork and it hasn't fixed it.

But I haven't adopted any of the previous changes eg [this one](https://github.com/shreyas-jadhav/roundware-web-template/commit/cb455504da25f525fa66e4bdbae7b3036ffeb9d4)

Is that the best code to use? Should I switch to that fork? Or at least copy/paste the changes.

**Comment by gavspav** [comment]
This seems to be fixed using the developer fork
