### ISSUE TITLE
Uncaught (in promise) TypeError: e.getNorthEast() is undefined

### ISSUE THREAD

**Issue by sbenthall** [roundware/roundware-web-template#14]
1. Connecting to https://roundware-web-template.vercel.app/ in Firefox from desktop
2. Click LISTEN
3. Click to allow the website to access my location. (Not sure what that does, since i"m on a desktop that's not geolocated?)
4. See this:
![image](https://user-images.githubusercontent.com/68752/197878235-312cf01b-fbde-4912-8ca4-af0facab541f.png)

5. Dutifully checking the JavaScript console to see what's wrong:
https://gist.github.com/sbenthall/299591277c9433f2195d3b481e8ed528

**Comment by hburgund** [comment]
the google maps API key being used here isn't allowed on the vercel domain, so any screen with a map is going to thrown an error.
The Vercel deploys are really just for my dev and I to do testing, so we focus on what we are working on leaving some stuff not working sometimes.
Not sure what you are using this deploy for though? I have other deploys that you could use for testing, but I presume that you want your own web app connected to your own RW server to be up and running for testing?

**Comment by sbenthall** [comment]
Yes, I'm also working on a local version.
But since I saw a link to the vercel app and found the error, I thought I'd report it.
I see now that there was no need to.
