### ISSUE TITLE
Possible to get two versions of a submitted file playing at the same time.

### ISSUE THREAD

**Issue by gavspav** [roundware/roundware-web-template#9]
For example if you press the play button after uploading a (long) clip, then submit the clip, then select 'listen' the clip will play twice.

**Comment by hburgund** [comment]
To be clear, you are using the "Upload" feature on the non-mobile version of the web app? Basically, the clip plays twice when you submit it while it is playing? Not sure I fully understand what causes this, but it should be easy to remedy with reproducible steps...thx.

**Comment by gavspav** [comment]
Yes upload with a non mobile version of the web app. Not sure if it is the same with recording from microphone.
To reproduce, select a file (ideally one of at least 30 seconds).
Then press the playback button so it plays back.

Then press submit (file is still playing back)
Then press listen and playback in the asset window. There are now two playback instances.

**Comment by hburgund** [comment]
thx...this should be easily fixed by adding a "stop any playback" call to the Submit button...

@shreyas-jadhav can you have a look at this whenever you get a chance?

**Comment by shreyas-jadhav** [comment]
This should be fixed here https://github.com/roundware/roundware-web-template/pull/11/commits/676910d8ced1b65dbda377bb420c2d81907621a2

**Comment by gavspav** [comment]
I think this does work yes! Although I found another bug which confused me.
